#!/bin/bash

#SBATCH --job-name=dmg       ## Name of the job.
#SBATCH -A ALLISONS_LAB       ## account to charge 
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=1    ## number of cores the job needs

#SBATCH --mail-type=end               ## send email when the job ends
#SBATCH --mail-user=bwang7@uci.edu    ## use this email address

#SBATCH --array=1                  ## number of array tasks

#SBATCH --output=std/%x_%A_%a.txt
##SBATCH --error=error_%A_%a.txt ## error log file name: %A is job id, %a is array task id



module purge
module load anaconda

cd src
python dementpy.py input_basesite output_basesite 2020$SLURM_ARRAY_TASK_ID site
